name: Deploy AI Model

on:
  push:
    branches:
      - main  # ya jo bhi branch tum use kar rahe ho

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ya jo version tum use kar rahe ho

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the model deployment script
        run: |
          python model.py  # Tumhare model code ko run karo
